---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.3.0

platforms:
  - name: centos-6.6
  - name: centos-7.0
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: upgrade
    run_list:
      recipe[omnibus_updater::default]
    attributes:
      omnibus_updater:
        version: '12.4.0'
        kill_chef_on_upgrade: false
  - name: downgrade
    run_list:
      recipe[omnibus_updater::default]
    attributes:
      omnibus_updater:
        version: '12.2.1'
        kill_chef_on_upgrade: false
